USE ergasia;

INSERT INTO roles (name) VALUES ('ROLE_STUDENT');
INSERT INTO roles (name) VALUES ('ROLE_PROFESSOR');
INSERT INTO roles (name) VALUES ('ROLE_COMPANY');
INSERT INTO roles (name) VALUES ('ROLE_COMMITTEE');